---
- name: Deploy Spring Boot App
  hosts: web
  become: yes

  tasks:

    - name: Copy jar
      copy:
        src: ../../target/your-app-0.0.1-SNAPSHOT.jar
        dest: /home/azureuser/your-app.jar
        mode: '0755'

    - name: Stop old app
      shell: |
        pkill -f your-app.jar || true
      ignore_errors: yes

    - name: Start app
      shell: |
        nohup java -jar /home/azureuser/your-app.jar --server.port=8081 > app.log 2>&1 &
